FROM ubuntu:24.04

RUN mkdir -p /app
WORKDIR /app

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install iproute2 net-tools php composer php8.3-xml php8.3-sqlite3 iproute2 netcat-traditional -y

COPY myapp myapp
ENV myapp_dir=/app/myapp
COPY myapp/run_env/start_app.bash /etc/start_scripts/start_app
ENTRYPOINT ["/etc/start_scripts/start_app"]
